### ISSUE TITLE
How to overwrite instance ip registered in polaris?

### ISSUE THREAD

**Issue by Andrew-M-C** [trpc-ecosystem/go-naming-polarismesh#16]
### Is your feature request related to a problem?

Related issue: #14 

### What is the solution you'd like?

My application was running in a docker container, with service bound to `nic: eth0`. The IP was `172.17.0.4`. And this is automatically registered in polaris:

![image](https://github.com/trpc-ecosystem/go-naming-polarismesh/assets/6083108/02535ce0-e29e-4fd3-902e-4f6d9cdde73d)

However this IP was not accessable outside docker container, thus I need to overwrite it.

There is a comment in [doc](https://github.com/trpc-ecosystem/go-naming-polarismesh/blob/main/README.zh_CN.md#配置完整示例):

```
#     bind_address: eth1:8080       # （可选）指定服务监听地址，默认采用 service 中的地址
```

I configured, but it did not take effect. 

### What alternatives have you considered?

I want to change the IP/port registered by polaris registery.

### Could you provide additional context?

Here is my configuration:

```yaml
plugins:
  registry:
    polarismesh:
      register_self: true
      heartbeat_interval: 1000
      protocol: grpc
      debug: true
      address_list: host.docker.internal:8091
      instance_location:
        region: China
        zone: Guangdong
        campus: Shenzhen
      service:
        - name: trpc.study.HelloWorld
          # instance_id: $HOSTNAME
          namespace: dev
          bind_address: host.docker.internal:8000 # no effect, 127.0.0.1:8000 either
          weight: 100
          token: not_needed
  selector:
    polarismesh:
      protocol: grpc
      address_list: host.docker.internal:8091
```
