### ISSUE TITLE
单进程多服务要怎么配置

### ISSUE THREAD

**Issue by manchurio** [trpc-ecosystem/go-naming-polarismesh#19]
```
如题,  在单进程多服务的时候, 配置文件tpc_go.yaml 
server/service 配置一个就可以, 但是在配置polaris插件registery的service要配置多个, 
```

```yaml
server:
  service:
    - name: trpc.helloworld #单进程多服务,这里我也只需要配置一个, 共用一个端口
      ip: 127.0.0.1
      port: 8001


plugins: #  
  registry:  
    polarismesh:  
      register_self: true  
      heartbeat_interval: 3000   
      address_list: "10.100.1.15:8091"
      debug: true  
      instance_location:  
        region: China
        zone: Guangdong
        campus: Shenzhen
      service: 
        - name: trpc.helloworld # 这里的name要和上面的name对应, 单进程有多个服务的时候这里要怎么配置
          namespace: ns-dev1   
          token: xxxxxxxxxxxxxxxxxxxx  
      config.
          instance_id: yyyyyyyyyyyyyyyy
          weight: 100 
```
